[package]
name = "hc_utils"
version = "0.5.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"

[lib]
name = "hc_utils"
crate-type = ["cdylib", "rlib"]

[dependencies]
hdk = "0.1.3-beta-rc.1"
