[package]
name = "hc_utils"
version = "0.7.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"

[lib]
name = "hc_utils"
crate-type = ["cdylib", "rlib"]

[dependencies]
hdk = "0.3.0-beta-dev.7"
