[package]
name = "portal"
version = "0.0.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"

[lib]
name = "portal"
crate-type = ["cdylib", "rlib"]

[dependencies]
essence_payloads = "0.1"
hc_crud_caps = { git = "https://github.com/mjbrisebois/rust-hc-crud-caps.git", rev = "10d042c36024e2d839008bdb621595a8c09f0b74" }
hc_utils = {path = "../../hc_utils"}
hdi = "0.2.3-beta-rc.0"
hdk = "0.1.3-beta-rc.1"
hc_portal_types = {path = "../../portal_types"}
serde = "1"
rmpv = { version = "1.0.0", features = ["with-serde"] }
thiserror = "1"
