[package]
name = "portal"
version = "0.0.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2021"

[lib]
name = "portal"
crate-type = ["cdylib", "rlib"]

[dependencies]
hc_crud_caps = "0.19"
hc_portal_types = { version = "0.17", path = "../../types" }
serde = "1"
